# LAB | Feature Engineering

**Load the data**

In this challenge, we will be working with the same Spaceship Titanic data, like the previous Lab. The data can be found here:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv

Metadata

https://github.com/data-bootcamp-v4/data/blob/main/spaceship_titanic.md

In [162]:
#Libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.neighbors import KNeighborsRegressor

In [163]:
spaceship = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/spaceship_titanic.csv")
spaceship.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

**Check the shape of your data**

In [164]:
spaceship.shape

(8693, 14)

**Check for data types**

In [165]:
spaceship.dtypes

PassengerId      object
HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
Name             object
Transported        bool
dtype: object

**Check for missing values**

In [166]:
((spaceship.isna().sum())/len(spaceship))*100

PassengerId     0.000000
HomePlanet      2.312205
CryoSleep       2.496261
Cabin           2.289198
Destination     2.093639
Age             2.059128
VIP             2.335212
RoomService     2.082135
FoodCourt       2.105142
ShoppingMall    2.392730
Spa             2.105142
VRDeck          2.162660
Name            2.300702
Transported     0.000000
dtype: float64

There are multiple strategies to handle missing data

- Removing all rows or all columns containing missing data.
- Filling all missing values with a value (mean in continouos or mode in categorical for example).
- Filling all missing values with an algorithm.

For this exercise, because we have such low amount of null values, we will drop rows containing any missing value.

In [167]:
spaceship=spaceship.dropna()

In [168]:
spaceship.shape

(6606, 14)

**Perform train test**

In [169]:
features = spaceship.drop(columns='Transported')
target = spaceship["Transported"]

In [170]:
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.20, random_state=17)

In [171]:
print(X_train.shape)
print(X_test.shape)

(5284, 13)
(1322, 13)

- **Cabin** is too granular - transform it in order to obtain {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'T'}

In [172]:
def cabin_value_handle(X_train):
    X_train['Cabin'] = X_train['Cabin'].str.split('/').str[0]
    return X_train


X_train=cabin_value_handle(X_train)

In [173]:
X_train['Cabin'].value_counts()

Cabin
F    1722
G    1589
E     549
B     500
C     464
D     292
A     167
T       1
Name: count, dtype: int64

- Drop PassengerId and Name

In [174]:
X_train

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name
1388,1455_03,Europa,True,B,55 Cancri e,22.0,False,0.0,0.0,0.0,0.0,0.0,Rotanin Wassird
1031,1097_01,Mars,True,E,TRAPPIST-1e,42.0,False,0.0,0.0,0.0,0.0,0.0,Tundsh Weeke
3717,3995_04,Earth,False,G,TRAPPIST-1e,8.0,False,0.0,0.0,0.0,0.0,0.0,Evey Casonston
2829,3054_01,Earth,False,F,TRAPPIST-1e,13.0,False,578.0,77.0,0.0,306.0,5.0,Celis Bootez
6236,6595_01,Earth,False,G,TRAPPIST-1e,35.0,False,102.0,780.0,6.0,0.0,0.0,Tyle Simstravery
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,1906_01,Earth,True,G,TRAPPIST-1e,14.0,False,0.0,0.0,0.0,0.0,0.0,Claura Booneid
536,0570_01,Europa,False,C,TRAPPIST-1e,36.0,True,530.0,5085.0,1.0,146.0,872.0,Chard Tramsor
7279,7784_01,Mars,True,F,TRAPPIST-1e,28.0,False,0.0,0.0,0.0,0.0,0.0,Cray Berte
2934,3182_01,Earth,False,F,TRAPPIST-1e,18.0,False,0.0,0.0,699.0,0.0,0.0,Herita Welltonces
3558,3823_01,Mars,False,F,TRAPPIST-1e,27.0,False,1192.0,0.0,0.0,0.0,0.0,Crisp Spore

In [175]:
def drop_pass_id(X_train):
    X_train = X_train.drop(columns=["PassengerId","Name"])
    return X_train

X_train = drop_pass_id(X_train)

In [176]:
#cecking column count now.previously it was 13
X_train.shape

(5284, 11)

- For non-numerical columns, do dummies.

1.dont we need to convert bool columns to int by one hot encoding?

In [177]:
X_train.dtypes

HomePlanet       object
CryoSleep        object
Cabin            object
Destination      object
Age             float64
VIP              object
RoomService     float64
FoodCourt       float64
ShoppingMall    float64
Spa             float64
VRDeck          float64
dtype: object

In [178]:
# CryoSleep and VIP has bool value but datatype is object so converting it to bool
def bool_type_conversion(X_train):
    X_train["CryoSleep"] = X_train["CryoSleep"].astype(bool)
    X_train["VIP"] = X_train["VIP"].astype(bool)
    return X_train

X_train = bool_type_conversion(X_train)

In [179]:
categorical_cols = X_train.select_dtypes('object')

In [180]:
categorical_cols.columns.tolist()

['HomePlanet', 'Cabin', 'Destination']

Now we need to do one hot encoding for these 3 columns

In [181]:
def one_hot_encoding(X_train):
    X_train_encoded = encoder.transform(X_train[categorical_cols.columns.tolist()])
    df=pd.DataFrame(X_train_encoded, columns=encoder.get_feature_names_out(categorical_cols.columns.tolist()))
    X_train = X_train.reset_index(drop=True)
    df = df.reset_index(drop=True)
    df = pd.concat([X_train, df], axis=1).reset_index(drop=True)
    df = df.drop(columns=['HomePlanet', 'Cabin', 'Destination'])
    print(df.shape)
    return df

encoder = OneHotEncoder(sparse_output = False)
encoder.fit(X_train[categorical_cols.columns.tolist()])
X_train_encoded = one_hot_encoding(X_train)

(5284, 22)

In [182]:
X_train_encoded

,CryoSleep,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,HomePlanet_Earth,HomePlanet_Europa,...,Cabin_B,Cabin_C,Cabin_D,Cabin_E,Cabin_F,Cabin_G,Cabin_T,Destination_55 Cancri e,Destination_PSO J318.5-22,Destination_TRAPPIST-1e
0,True,22.0,False,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,True,42.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,False,8.0,False,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,False,13.0,False,578.0,77.0,0.0,306.0,5.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
4,False,35.0,False,102.0,780.0,6.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5279,True,14.0,False,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
5280,False,36.0,True,530.0,5085.0,1.0,146.0,872.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
5281,True,28.0,False,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5282,False,18.0,False,0.0,0.0,699.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
5283,False,27.0,False,1192.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [183]:
X_train_encoded.shape

(5284, 22)

**Model Selection**

In this exercise we will be using **KNN** as our predictive model.

In [184]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 10)

In [185]:
knn.fit(X_train_encoded,y_train)

KNeighborsClassifier(n_neighbors=10)

- Evaluate your model's performance. Comment it

Do all transformations on test set also

In [186]:
X_test = cabin_value_handle(X_test)
X_test = drop_pass_id(X_test)
X_test = bool_type_conversion(X_test)
X_test = one_hot_encoding(X_test)

(1322, 22)

In [187]:
knn.score(X_test, y_test)

0.7987897125567323


got accuracy score 0.79 which tells model is getting good accuracy